# Generated by Django 3.0.8 on 2020-07-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('comment', models.TextField(max_length=500)),
                ('listing', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=500)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('image', models.CharField(max_length=500)),
                ('owner', models.CharField(default='SOME STRING', max_length=64)),
            ],
        ),
    ]
