# Generated by Django 3.0.8 on 2020-07-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200712_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='winner',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
